### PR TITLE
Add PHP open tags for better reading

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by glensc** [comment]
seems pointless. github already [highlights this](https://github.com/facebookarchive/facebook-php-sdk/blob/master/readme.md#usage) using:

``````
```php
```
``````

**Comment by bocharsky-bw** [comment]
@glensc You're right, thanks!
I think many people copy the code from this file and it will be better to add `<?php` to avoid possible problems, especially with beginners.
@glensc what do you think?

**Comment by glensc** [comment]
but the samples are not full file, the are to be inserted to existing php script

**Comment by bocharsky-bw** [comment]
@glensc not always, developers could try this lib in scratch first before to use it in real project.

**Comment by gfosco** [comment]
Closing this issue as this repository is archived.  The current version of the SDK can be found at facebook/facebook-php-sdk-v4

**Pull request closed without merging**
